// const shoesProduct = [
//     {
//         productname: "CLOUDFOAM PURE SHOES",
//         mindetail: "Cloud White / Chalk White / Zero Metalic",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Addidas",
//         price: 75,
//         qunty: "300",
//         pay: "price_1NVC32CU5RaAZNMDZJrvphca",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct1Maain.png?alt=media&token=57390b99-b996-41f8-a184-472b5c21bc90",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct1min.avif?alt=media&token=ed10ebe1-f8ab-4672-a420-b7783434c91a",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct1min2.avif?alt=media&token=646b21ab-54c4-4d67-ae1d-9b463c8990c3",
//         ],
//     },
//     {
//         productname: "HOOPS 3.0 LOW CLASSIC VINTAGE SHOES",
//         mindetail: "Grey Two / Collegiate Green / Cloud White",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Addidas",
//         price: 70,
//         qunty: "300",
//         pay: "price_1NVEVLCU5RaAZNMDEbAPfvBU",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct3Main.avif?alt=media&token=cfb8a965-e230-4bf1-8756-265ed419502f",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct3min.avif?alt=media&token=e37feb31-9441-40a0-ac0c-4804f90f29bd",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct3min2.avif?alt=media&token=44b07f4d-a206-46b8-82c2-6f0081321efd",
//         ],
//     },
//     {
//         productname: "DAILY 3.0 SHOES",
//         mindetail: "Shadow Brown / Preloved Brown / Cloud White",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Addidas",
//         price: 65,
//         qunty: "200",
//         pay: "price_1NVEkSCU5RaAZNMDN9k6faYo",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct4main.avif?alt=media&token=e7267dcd-3119-4d5b-b872-4cf9e4eefd68",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct4min.avif?alt=media&token=298d74ae-7575-4221-8bc3-7940feced493",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct4min2.avif?alt=media&token=b0af69de-42cf-43db-8116-601d90bea535",
//         ],
//     },
//     {
//         productname: "KAPTIR 3.0 SHOES",
//         mindetail: "Core Black / Screaming Orange / Shadow Olive",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Addidas",
//         price: 90,
//         qunty: "400",
//         pay: "price_1NVF3HCU5RaAZNMDn6cfy7jX",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct5main.avif?alt=media&token=76c8eb87-50d3-4493-9573-731d5fce55a2",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct5min.avif?alt=media&token=bb233576-fa65-47dd-b23d-a6c87c56f801",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct5min2.avif?alt=media&token=f39d2900-80ae-47a4-b17f-376115c52d39",
//         ],
//     },
//     {
//         productname: "Y-3 GAZELLE",
//         mindetail: "Cloud White / Chalk White / Zero Metalic",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Addidas",
//         price: 300,
//         qunty: "240",
//         pay: "price_1NVFLGCU5RaAZNMDNqmbAmLj",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct6main.avif?alt=media&token=1926d8ed-373d-4989-9462-a9d2e1f0ccd4",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct6min.avif?alt=media&token=3e3729a5-bf63-425e-940f-f16c0fd539b0",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct6min2.avif?alt=media&token=6bd06229-22b0-453a-af79-5e82448b86d0",
//         ],
//     },
//     {
//         productname: "RACER TR23 SHOES",
//         mindetail: "Dark Blue / Cloud White / Halo Silver",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Nike",
//         price: 80,
//         qunty: "390",
//         pay: "price_1NVFgCCU5RaAZNMDao7BgCn7",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct7main.avif?alt=media&token=75513f13-1d32-450f-8333-fb3b66100061",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct7min.avif?alt=media&token=c6765dc4-e40a-469d-a46a-9dc56515f99b",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct7min2.avif?alt=media&token=6e185bb1-455b-4f3c-ac7e-504010275036",
//         ],
//     },
//     {
//         productname: "KANTANA SHOES",
//         mindetail: "Chalk White / Wonder Clay / Wonder Quartz",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Nike",
//         price: 90,
//         qunty: "327",
//         pay: "price_1NVFpyCU5RaAZNMDyHWB8qKn",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct8main.avif?alt=media&token=c78d67b3-02ed-4e49-924a-083889aab78b",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct8min.avif?alt=media&token=cb6ce1bf-2b48-4c23-b598-1cea5c9e4c64",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct8min2.avif?alt=media&token=8970eda6-5939-4053-a11b-38574ee64c39",
//         ],
//     },
//     {
//         productname: "ADILETTE SANDALS",
//         mindetail: "Core Black / Cloud White / Core Black",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Nike",
//         price: 40,
//         qunty: "100",
//         pay: "price_1NVFyWCU5RaAZNMDgrBj2JEL",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct9main.png?alt=media&token=cfb49f49-4ebb-4cdf-99ce-d02b9ab09655",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct9min.avif?alt=media&token=7bc82caa-d12b-4b73-9274-158de43b76e6",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct9min2.avif?alt=media&token=82d666b9-8f57-4332-86e0-208c0561acf6",
//         ],
//     },
//     {
//         productname: "GAZELLE SHOES",
//         mindetail: "Silver Dawn / Cloud White / Core Black",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Nike",
//         price: 100,
//         qunty: "100",
//         pay: "price_1NVG7gCU5RaAZNMDoYEmZpED",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct10main.png?alt=media&token=db5ad18d-89d1-49ba-9491-9c806be947be",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct10min.avif?alt=media&token=7515fba4-3373-483f-9dcb-c8b89a773591",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct10min2.avif?alt=media&token=f92e7667-03b3-460d-afa5-88de711e0786",
//         ],
//     },
//     {
//         productname: "RUNFALCON 2.0 SHOES",
//         mindetail: "Cloud White / Vision Met. / Signal Green",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Nike",
//         price: 50,
//         qunty: "300",
//         pay: "price_1NVGIgCU5RaAZNMD0gOtprdy",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct11main.avif?alt=media&token=27367286-7570-4100-babe-02a66c791ba2",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct11min.avif?alt=media&token=3e462f43-f7a3-456f-b918-eac71c98bd0c",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct11min2.avif?alt=media&token=0c7153d9-063d-44cd-8bfc-c4643c7217d9",
//         ],
//     },
//     {
//         productname: "ULTRABOOST 1.0 SHOES",
//         mindetail: "Silver Green / Silver Green / Olive Strata",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Service",
//         price: 140,
//         qunty: "120",
//         pay: "price_1NVGYjCU5RaAZNMDANOe4Hvz",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct12main.avif?alt=media&token=bbeddfbb-90ce-4432-8272-55988e9eb00b",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct12min.avif?alt=media&token=221004da-4ca6-4c18-a246-4af43c1c6cfa",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct12min2.avif?alt=media&token=1231e31f-2f99-4d24-95d2-29cbca223c4f",
//         ],
//     },
//     {
//         productname: "ULTRABOOST 1.0 ARIZONA STATE",
//         mindetail: "Cloud White / Team Maroon / Team Colleg Gold",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Service",
//         price: 140,
//         qunty: "123",
//         pay: "price_1NVGjHCU5RaAZNMD1eURpq4j",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct13main.avif?alt=media&token=e2ff5e69-9671-4e92-8a4f-fde2564de76a",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct13min.avif?alt=media&token=6d0d897c-2435-4816-acea-5394608d8e3d",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct13min2.avif?alt=media&token=35afd712-84c6-4b6c-827d-add89cbf8837",
//         ],
//     },
//     {
//         productname: "FORUM BONEGA SHOES",
//         mindetail: "Cloud White / Royal Blue / Gold Metallic",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Service",
//         price: 120,
//         qunty: "123",
//         pay: "price_1NVH4OCU5RaAZNMDwpsooSAX",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct14main.avif?alt=media&token=c84d6ac3-2cf9-4659-bd50-e9ff47827704",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct14min.avif?alt=media&token=1a49f627-00e3-4197-b6a9-0e3eacb6d8af",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct14min2.avif?alt=media&token=8bf8dc87-f615-4dd6-8907-e3978ae99d8d",
//         ],
//     },
//     {
//         productname: "X_PLRBOOST SHOES",
//         mindetail: "Core Black / Cloud White / Pulse Lime",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Service",
//         price: 128,
//         qunty: "120",
//         pay: "price_1NVHJ7CU5RaAZNMDWpHnxXSD",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct14main.avif?alt=media&token=c84d6ac3-2cf9-4659-bd50-e9ff47827704",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct14min.avif?alt=media&token=1a49f627-00e3-4197-b6a9-0e3eacb6d8af",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct14min2.avif?alt=media&token=8bf8dc87-f615-4dd6-8907-e3978ae99d8d",
//         ],
//     },
//     {
//         productname: "X_PLRBOOST SHOES",
//         mindetail: "Core Black / Cloud White / Pulse Lime",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Service",
//         price: 128,
//         qunty: "120",
//         pay: "price_1NVHJ7CU5RaAZNMDWpHnxXSD",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct15main.avif?alt=media&token=df4c7a51-fcb5-4a1d-952f-acb93e12b480",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct15min.avif?alt=media&token=83cc0c2f-f990-4a92-8fa2-8bbb86f728a4",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct15min2.avif?alt=media&token=7c4ac91e-9a41-46f6-91a5-da967bbf5cb4",
//         ],
//     },
//     {
//         productname: "LITE RACER ADAPT 4.0 CLOUDFOAM SLIP-ON SHOES",
//         mindetail: "Better Scarlet / Core Black / Cloud White",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Service",
//         price: 70,
//         qunty: "290",
//         pay: "price_1NVI5LCU5RaAZNMDOqOlWz10",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct1Maain.png?alt=media&token=57390b99-b996-41f8-a184-472b5c21bc90",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct1min.avif?alt=media&token=ed10ebe1-f8ab-4672-a420-b7783434c91a",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct1min2.avif?alt=media&token=646b21ab-54c4-4d67-ae1d-9b463c8990c3",
//         ],
//     },
//     {
//         productname: "LITE RACER ADAPT 4.0 CLOUDFOAM SLIP-ON SHOES",
//         mindetail: "Better Scarlet / Core Black / Cloud White",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Service",
//         price: 70,
//         qunty: "290",
//         pay: "price_1NVI5LCU5RaAZNMDOqOlWz10",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [

//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct15main.avif?alt=media&token=df4c7a51-fcb5-4a1d-952f-acb93e12b480",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct15min.avif?alt=media&token=83cc0c2f-f990-4a92-8fa2-8bbb86f728a4",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct15min2.avif?alt=media&token=7c4ac91e-9a41-46f6-91a5-da967bbf5cb4",
//         ],
//     },
//     {
//         productname: "LITE RACER ADAPT 4.0 Bata SHOES",
//         mindetail: "Better Scarlet / Core Black / Cloud White",
//         fulldetail: "very comfertable and soft shoes easy to wear  and good for walk",
//         catagory: "Bata",
//         price: 270,
//         qunty: "290",
//         pay: "price_1NVI5LCU5RaAZNMDOqOlWz10",
//         sizes: [
//             "UK 6",
//             "UK 6.5",
//             "UK 7",
//             "UK7.5",
//             "UK 8",
//             "UK 8.5",
//             "UK 9",
//             "UK 11.5",
//             "UK 11.5",
//             "UK 9.5",
//             "UK 10",
//             "UK 10.5",
//             "UK 11",
//             "UK 11.5",
//         ],
//         images: [
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/image%2Fproduct15main.avif?alt=media&token=df4c7a51-fcb5-4a1d-952f-acb93e12b480",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageT%2Fproduct15min.avif?alt=media&token=83cc0c2f-f990-4a92-8fa2-8bbb86f728a4",
//             "https://firebasestorage.googleapis.com/v0/b/web-chat-app-b5031.appspot.com/o/imageTh%2Fproduct15min2.avif?alt=media&token=7c4ac91e-9a41-46f6-91a5-da967bbf5cb4",                
//         ],
//     },
// ]



// AddiasProduct.insertMany(shoesProduct).then(() => {
//     console.log('Data inserted');
// }).catch((err) => {
//     console.log(err);
// })


// get all AddiasProduct
